// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fctarpegeatdizeuzzyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjdGFycGVnZWF0ZGl6ZXV6enliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTUwNTgsImV4cCI6MjA2ODQzMTA1OH0.uLx4ezEifb790eY3VqLuUyGTi6js3MTRio0yXZCvsI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});